### ISSUE TITLE
running 'osxiso' creates deps/osxiso/package.json only

### ISSUE THREAD

**Issue by gw666** [busterc/osx-iso#1]
Hi--hope you can help me with this. I installed bpkg, confirmed that it worked by using it to install term. Then I executed the following:

```
gw-mac-pro:~ gr$ bpkg install busterc/osx-iso

    info: Install /busterc/osx-iso/master from remote https://raw.githubusercontent.com [https://github.com]
gw-mac-pro:~ gr$ osxiso Mavericks
-bash: osxiso: command not found
gw-mac-pro:~ gr$
```
I searched my computer for "osxiso" and found the single file deps/osxiso/package.json.

I tried the install and run commands again (because I didn't know what else to try), with the same lack of result.

Any ideas? Thanks!

**Comment by busterc** [comment]
It looks like `bpkg` updated their installation processes. I've updated the README, with the latest release (version 3), to include the required `-g` CLI argument:

`$ bpkg install busterc/osx-iso -g`
