### ISSUE TITLE
monterey 12.1 broken ?

### ISSUE THREAD

**Issue by devZer0** [busterc/osx-iso#9]
hi, 

has monterey 12.1 successfully being tested ?

i first got an error (ufortunately didn't remember what exact) while creating the iso and then by trying to troubleshoot the error , for my curiosity it worked after i added "set -x" to the script. it also worked after removing set -x , i.e. i could not reproduce the error. 

iso got created and i can select to boot from the iso with my iodd/zalman external hdd , but then i got  no-parking-sign (crossed out circle) with "support.apple.com/mac/startup" underneath

thanks

**Comment by busterc** [comment]
> it worked after i added "set -x" to the script

^ I don't know why you needed to do this. It's never a problem for me when I clone this repo or install via Homebrew.

> boot from the iso with my iodd/zalman external hdd , but then i got no-parking-sign (crossed out circle) with "support.apple.com/mac/startup" underneath

^ I've never seen this and you're the first to report it. It seems like there might be some sort of hardware conflict. What are your Mac's specs and OS version?

**Comment by devZer0** [comment]
>It seems like there might be some sort of hardware conflict

yes. apparently. 

it's a 2014 macbook pro and i just read that you need at least 2015 mbp for montery. 

stupid installer. 

building some "this hardware is too old" error message apparently is too difficult too develop.   early boot/installer error messages with apple have always been cryptic.....

i grabbed a 2015 macbook and all is fine

sorry for the noise.
